# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Person.create(name: 'Nicole Kulick', title: 'GRAD SCHOOL STUDENT, FUTURE SCHOOL COUNSELOR & A BUNDLE OF AWESOME', description: '<p>Born and raised in Columbus, Ohio. Supported by two loving parents, Dan and Donna Coontz.</p><p>Extroverted. Enthusiastic. Hysterical.</p><p><strong>Likes</strong>: farmer\'s markets, horror movies, and donuts.</p><p><strong>Dislikes</strong>: mean people, oatmeal, and rolled-under toiletpaper</p>', photo: 'images/nicole.jpg')
Person.create(name: 'Craig Wermert', title: 'SOFTWARE DEVELOPER & TALL GUY', description: '<p>Born and raised in Sidney, Ohio. Son of two loving parents, Carl and Rosie Wermert.</p><p>Amazing. Incredible. Humble.</p><p><strong>Likes</strong>: music, bad horror movies, and writing code (i.e. he\'s a nerd)</p><p><strong>Dislikes</strong>: tomatoes, clowns, and Nicole\'s nightly impromptu serenades</p>', photo: 'images/craig.jpg')

Story.create(title: 'The Beginning', time: 'March, 2012', icon: 'mail', iconColor: '#3498db', content: '<p>Who knew cupid would be real? OkCupid that is!</p><p>Craig joined to see what would happen and meet new people. Nicole joined after a bit of peer pressure from her coworkers.</p><p>She messaged him, he messaged back. And then, the awesomeness began.</p>')
Story.create(title: 'First Date', time: 'A few weeks later in March, 2012', icon: 'heart',iconColor: '#e74c3c', content: '<p>After a few drinks, Craig parallel parking Nicole\'s car, and some pizza at Plank\'s, they called it a night. By all accounts, the first date was a success. </p>')
Story.create(title: 'Craig Moves In', time: 'October, 2012', icon: 'truck', iconColor: '#34495e', content: '<p>By this time, they were in love.</p><p>Despite Nicole\'s hesitation regarding toilet seats left ajar and socks on the living room floor, Craig packed up his belongings and moved in with Nicole. Craig told her she had nothing to worry about. <strong><em>Craig was right.</em></strong>')
Story.create(title: 'Awesome Quiet Time', time: 'October, 2012 - March, 2014', icon: 'clock', iconColor: '#16a085', content: '<p>Other than day-to-day love and totally being awesome, not much happened in their relationship during this period. Nicole went back to school for her Master\'s degree, and Craig started working as a software engineer.</p>')
Story.create(title: 'The Question', time: 'March 8th, 2014', icon: 'diamond', iconColor: '#3498db', content: '<p>It was the biggest day of their lives (to this point, at least). Since the two are romantics at heart, it went something like this...</p><p><strong>Nicole</strong>: “What\'s wrong; do you have to poop?”</p><p><strong>Craig</strong>: “No, I was actually wondering if you\'d marry me?”</p><p><strong>Nicole</strong>: “Shut up! Are you kidding?!”</p><p><strong>Craig</strong>: “…”</p><p><strong>Nicole</strong>: “Yes!”</p>')